# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pneumainfowidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VehicleInfo(object):
    def setupUi(self, VehicleInfo):
        VehicleInfo.setObjectName("VehicleInfo")
        VehicleInfo.resize(1262, 150)
        self.gridLayout = QtWidgets.QGridLayout(VehicleInfo)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(VehicleInfo)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(VehicleInfo)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.selectedIDLineEdit = QtWidgets.QLineEdit(VehicleInfo)
        self.selectedIDLineEdit.setReadOnly(True)
        self.selectedIDLineEdit.setObjectName("selectedIDLineEdit")
        self.gridLayout.addWidget(self.selectedIDLineEdit, 0, 1, 1, 1)
        self.selectedTypeLineEdit = QtWidgets.QLineEdit(VehicleInfo)
        self.selectedTypeLineEdit.setReadOnly(True)
        self.selectedTypeLineEdit.setObjectName("selectedTypeLineEdit")
        self.gridLayout.addWidget(self.selectedTypeLineEdit, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(VehicleInfo)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 4, 1, 1)
        self.selectedXPosLineEdit = QtWidgets.QLineEdit(VehicleInfo)
        self.selectedXPosLineEdit.setReadOnly(True)
        self.selectedXPosLineEdit.setObjectName("selectedXPosLineEdit")
        self.gridLayout.addWidget(self.selectedXPosLineEdit, 0, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(VehicleInfo)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 6, 1, 1)
        self.selectedYPosLineEdit = QtWidgets.QLineEdit(VehicleInfo)
        self.selectedYPosLineEdit.setReadOnly(True)
        self.selectedYPosLineEdit.setObjectName("selectedYPosLineEdit")
        self.gridLayout.addWidget(self.selectedYPosLineEdit, 0, 7, 1, 1)
        self.label_12 = QtWidgets.QLabel(VehicleInfo)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 0, 1, 1)
        self.selectedVelLineEdit = QtWidgets.QLineEdit(VehicleInfo)
        self.selectedVelLineEdit.setReadOnly(True)
        self.selectedVelLineEdit.setObjectName("selectedVelLineEdit")
        self.gridLayout.addWidget(self.selectedVelLineEdit, 1, 1, 1, 1)
        self.selectedHeadingLineEdit = QtWidgets.QLineEdit(VehicleInfo)
        self.selectedHeadingLineEdit.setReadOnly(True)
        self.selectedHeadingLineEdit.setObjectName("selectedHeadingLineEdit")
        self.gridLayout.addWidget(self.selectedHeadingLineEdit, 1, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(VehicleInfo)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(VehicleInfo)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 4, 1, 1)
        self.selectedLatAccLineEdit = QtWidgets.QLineEdit(VehicleInfo)
        self.selectedLatAccLineEdit.setReadOnly(True)
        self.selectedLatAccLineEdit.setObjectName("selectedLatAccLineEdit")
        self.gridLayout.addWidget(self.selectedLatAccLineEdit, 1, 5, 1, 1)
        self.label_15 = QtWidgets.QLabel(VehicleInfo)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 1, 6, 1, 1)
        self.selectedLonAccLineEdit = QtWidgets.QLineEdit(VehicleInfo)
        self.selectedLonAccLineEdit.setReadOnly(True)
        self.selectedLonAccLineEdit.setObjectName("selectedLonAccLineEdit")
        self.gridLayout.addWidget(self.selectedLonAccLineEdit, 1, 7, 1, 1)

        self.retranslateUi(VehicleInfo)
        QtCore.QMetaObject.connectSlotsByName(VehicleInfo)

    def retranslateUi(self, VehicleInfo):
        _translate = QtCore.QCoreApplication.translate
        VehicleInfo.setWindowTitle(_translate("VehicleInfo", "Form"))
        self.label_5.setText(_translate("VehicleInfo", "ID:"))
        self.label_6.setText(_translate("VehicleInfo", "Type:"))
        self.label_10.setText(_translate("VehicleInfo", "X position:"))
        self.label_11.setText(_translate("VehicleInfo", "Y Position:"))
        self.label_12.setText(_translate("VehicleInfo", "Velocity"))
        self.label_13.setText(_translate("VehicleInfo", "Heading:"))
        self.label_14.setText(_translate("VehicleInfo", "Lat acceleration:"))
        self.label_15.setText(_translate("VehicleInfo", "Lon acceleration:"))
